### ISSUE TITLE
Duplicate Step Definition

### ISSUE THREAD

**Issue by jesusvallez** [masmovil/cucumber-testcafe#6]
When you try to overwrite a step definition, cucumber does not know which step is the right one

![image](https://user-images.githubusercontent.com/19146593/66802917-5a075c80-ef1e-11e9-84ab-b3803e036f8b.png)

That is a problem because first one is implementing BasePO and last one ThorBasePO

**Comment by anthanh** [comment]
We should not have duplicated steps definition as long they have different behavior.
